
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class S_Analyzer extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Symbols.class;
}

  /** Default constructor. */
  @Deprecated
  public S_Analyzer() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public S_Analyzer(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public S_Analyzer(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\016\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\002\003\000\002\002\003\000\002\003\061" +
    "\000\002\004\051\000\002\005\004\000\002\005\003\000" +
    "\002\006\051\000\002\007\051\000\002\010\003\000\002" +
    "\010\003\000\002\010\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\145\000\004\004\010\001\002\000\004\002\ufffe\001" +
    "\002\000\004\002\000\001\002\000\004\002\ufffd\001\002" +
    "\000\004\002\uffff\001\002\000\004\006\013\001\002\000" +
    "\004\002\012\001\002\000\004\002\001\001\002\000\004" +
    "\010\014\001\002\000\004\011\015\001\002\000\004\007" +
    "\016\001\002\000\004\013\017\001\002\000\004\012\020" +
    "\001\002\000\004\013\021\001\002\000\004\006\022\001" +
    "\002\000\004\005\023\001\002\000\004\004\024\001\002" +
    "\000\004\014\025\001\002\000\004\015\026\001\002\000" +
    "\004\016\027\001\002\000\004\013\030\001\002\000\012" +
    "\026\034\036\033\037\031\040\032\001\002\000\004\013" +
    "\ufff6\001\002\000\004\013\ufff5\001\002\000\004\013\ufff4" +
    "\001\002\000\004\013\076\001\002\000\004\013\036\001" +
    "\002\000\004\005\037\001\002\000\004\017\040\001\002" +
    "\000\004\013\041\001\002\000\004\027\042\001\002\000" +
    "\004\013\043\001\002\000\004\016\044\001\002\000\004" +
    "\021\045\001\002\000\004\017\046\001\002\000\004\013" +
    "\047\001\002\000\004\030\050\001\002\000\004\013\051" +
    "\001\002\000\004\016\052\001\002\000\004\013\053\001" +
    "\002\000\006\024\054\025\055\001\002\000\004\013\066" +
    "\001\002\000\004\013\056\001\002\000\004\020\057\001" +
    "\002\000\004\022\060\001\002\000\004\020\061\001\002" +
    "\000\004\004\062\001\002\000\004\033\063\001\002\000" +
    "\004\014\064\001\002\000\004\005\065\001\002\000\004" +
    "\002\ufff7\001\002\000\004\020\067\001\002\000\004\022" +
    "\070\001\002\000\004\020\071\001\002\000\004\004\072" +
    "\001\002\000\004\033\073\001\002\000\004\014\074\001" +
    "\002\000\004\005\075\001\002\000\004\002\ufff8\001\002" +
    "\000\004\005\077\001\002\000\004\017\100\001\002\000" +
    "\004\013\101\001\002\000\004\027\102\001\002\000\004" +
    "\013\103\001\002\000\004\016\104\001\002\000\004\021" +
    "\105\001\002\000\004\017\106\001\002\000\004\013\107" +
    "\001\002\000\004\030\110\001\002\000\004\013\111\001" +
    "\002\000\004\016\112\001\002\000\004\013\113\001\002" +
    "\000\006\024\114\025\115\001\002\000\004\013\126\001" +
    "\002\000\004\013\116\001\002\000\004\020\117\001\002" +
    "\000\004\022\120\001\002\000\004\020\121\001\002\000" +
    "\004\004\122\001\002\000\004\033\123\001\002\000\004" +
    "\014\124\001\002\000\004\005\125\001\002\000\004\002" +
    "\ufffb\001\002\000\004\023\127\001\002\000\004\013\130" +
    "\001\002\000\004\031\131\001\002\000\004\013\132\001" +
    "\002\000\004\016\133\001\002\000\004\013\134\001\002" +
    "\000\004\032\135\001\002\000\006\013\ufff9\032\135\001" +
    "\002\000\004\013\137\001\002\000\004\020\140\001\002" +
    "\000\004\022\141\001\002\000\004\020\142\001\002\000" +
    "\004\004\143\001\002\000\004\033\144\001\002\000\004" +
    "\014\145\001\002\000\004\005\146\001\002\000\004\002" +
    "\ufffc\001\002\000\004\013\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\145\000\014\002\010\003\004\004\006\006\003\007" +
    "\005\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\034\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\135\001\001\000" +
    "\004\005\146\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$S_Analyzer$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$S_Analyzer$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$S_Analyzer$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static String resultado = null;
    public static String usuario = null;

    public static String nameUser = null;
    public static String passwordUser = null;
    public static String name = null;
    public static String institution = null;
    public static String date = null;

    //Metodo al que se llama automaticamente ante algun error sintactico
    public void syntax_error(Symbol s)
    {
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;

        System.out.println("!!!!!!! Error Sintactico Recuperado !!!!!!!");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);

    }

    //Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;

        System.out.println("!!!!!!! Error Sintactico, Panic Mode !!!!!!! ");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);

    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$S_Analyzer$actions {



  private final S_Analyzer parser;

  /** Constructor */
  CUP$S_Analyzer$actions(S_Analyzer parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$S_Analyzer$do_action_part00000000(
    int                        CUP$S_Analyzer$act_num,
    java_cup.runtime.lr_parser CUP$S_Analyzer$parser,
    java.util.Stack            CUP$S_Analyzer$stack,
    int                        CUP$S_Analyzer$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$S_Analyzer$result;

      /* select the action based on the action number */
      switch (CUP$S_Analyzer$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)).value;
		RESULT = start_val;
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$S_Analyzer$parser.done_parsing();
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= CORRECTO 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= INCORRECTO 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INICIO ::= AGREGARCORRECTO 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INICIO ::= AGREGARINCORRECTO 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // CORRECTO ::= LessThan QuestionMark XSONsentence Version Equal QuotationMark VersionNumber QuotationMark QuestionMark GreaterThan LessThan ExclamationMark RealizarSolicitud Colon QuotationMark LoginUsuario QuotationMark GreaterThan LeftBrace QuotationMark Respuesta QuotationMark Colon LeftBracket LeftBrace QuotationMark Status QuotationMark Colon QuotationMark Ok QuotationMark Comma QuotationMark Usuario QuotationMark Colon QuotationMark NAME QuotationMark RightBrace RightBracket RightBrace LessThan FinSolicitud ExclamationMark GreaterThan 
            {
              String RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).value;
		System.out.println("Sentencia correcta y aceptada");
            resultado = "Correcto";
            usuario = name;
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("CORRECTO",1, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-46)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INCORRECTO ::= LessThan QuestionMark XSONsentence Version Equal QuotationMark VersionNumber QuotationMark QuestionMark GreaterThan LessThan ExclamationMark RealizarSolicitud Colon QuotationMark LoginUsuario QuotationMark GreaterThan LeftBrace QuotationMark Respuesta QuotationMark Colon LeftBracket LeftBrace QuotationMark Status QuotationMark Colon QuotationMark Error QuotationMark RightBrace RightBracket RightBrace LessThan FinSolicitud ExclamationMark GreaterThan 
            {
              String RESULT =null;
		System.out.println("Sentencia correcta y password incorrecta");
                resultado = "Incorrecto";
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("INCORRECTO",2, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-38)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NAME ::= Name NAME 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.peek()).value;
		RESULT = String.valueOf(a) + " " + String.valueOf(b);
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("NAME",3, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // NAME ::= Name 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.peek()).value;
		RESULT = String.valueOf(a);
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("NAME",3, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // AGREGARCORRECTO ::= LessThan QuestionMark XSONsentence Version Equal QuotationMark VersionNumber QuotationMark QuestionMark GreaterThan LessThan ExclamationMark RealizarSolicitud Colon QuotationMark REQUESTS QuotationMark GreaterThan LeftBrace QuotationMark Respuesta QuotationMark Colon LeftBracket LeftBrace QuotationMark Status QuotationMark Colon QuotationMark Ok QuotationMark RightBrace RightBracket RightBrace LessThan FinSolicitud ExclamationMark GreaterThan 
            {
              String RESULT =null;
		System.out.println("Sentencia UsuarioNuevo, EliminarUsuario o NuevaTrivia correcta y aceptada");
                    resultado = "Correcto";
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("AGREGARCORRECTO",4, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-38)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // AGREGARINCORRECTO ::= LessThan QuestionMark XSONsentence Version Equal QuotationMark VersionNumber QuotationMark QuestionMark GreaterThan LessThan ExclamationMark RealizarSolicitud Colon QuotationMark REQUESTS QuotationMark GreaterThan LeftBrace QuotationMark Respuesta QuotationMark Colon LeftBracket LeftBrace QuotationMark Status QuotationMark Colon QuotationMark Error QuotationMark RightBrace RightBracket RightBrace LessThan FinSolicitud ExclamationMark GreaterThan 
            {
              String RESULT =null;
		System.out.println("Sentencia correcta, usuario ya existe");
                      resultado = "Incorrecto";
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("AGREGARINCORRECTO",5, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-38)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // REQUESTS ::= EliminarUsuario 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("REQUESTS",6, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // REQUESTS ::= NuevaTrivia 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("REQUESTS",6, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // REQUESTS ::= UsuarioNuevo 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("REQUESTS",6, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$S_Analyzer$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$S_Analyzer$do_action(
    int                        CUP$S_Analyzer$act_num,
    java_cup.runtime.lr_parser CUP$S_Analyzer$parser,
    java.util.Stack            CUP$S_Analyzer$stack,
    int                        CUP$S_Analyzer$top)
    throws java.lang.Exception
    {
              return CUP$S_Analyzer$do_action_part00000000(
                               CUP$S_Analyzer$act_num,
                               CUP$S_Analyzer$parser,
                               CUP$S_Analyzer$stack,
                               CUP$S_Analyzer$top);
    }
}

}
