
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

import java_cup.runtime.Symbol;
import java.util.LinkedList;
import models.login;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class S_Analyzer_main extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Symbols_main.class;
}

  /** Default constructor. */
  @Deprecated
  public S_Analyzer_main() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public S_Analyzer_main(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public S_Analyzer_main(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\016\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\002\003\000\002\002\003\000\002\006\061" +
    "\000\002\004\071\000\002\005\051\000\002\003\101\000" +
    "\002\007\003\000\002\007\003\000\002\011\002\000\002" +
    "\010\005\000\002\010\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\253\000\004\004\010\001\002\000\004\002\ufffe\001" +
    "\002\000\004\002\uffff\001\002\000\004\002\000\001\002" +
    "\000\004\002\ufffd\001\002\000\004\006\013\001\002\000" +
    "\004\002\012\001\002\000\004\002\001\001\002\000\004" +
    "\010\014\001\002\000\004\011\015\001\002\000\004\007" +
    "\016\001\002\000\004\013\017\001\002\000\004\012\020" +
    "\001\002\000\004\013\021\001\002\000\004\006\022\001" +
    "\002\000\004\005\023\001\002\000\004\004\024\001\002" +
    "\000\004\014\025\001\002\000\004\015\026\001\002\000" +
    "\004\016\027\001\002\000\004\013\030\001\002\000\012" +
    "\017\033\020\031\021\032\022\034\001\002\000\004\013" +
    "\207\001\002\000\004\013\160\001\002\000\004\013\076" +
    "\001\002\000\004\013\035\001\002\000\004\005\036\001" +
    "\002\000\004\023\037\001\002\000\004\013\040\001\002" +
    "\000\004\036\041\001\002\000\004\013\042\001\002\000" +
    "\004\016\043\001\002\000\004\025\044\001\002\000\004" +
    "\023\045\001\002\000\004\013\046\001\002\000\004\032" +
    "\047\001\002\000\004\013\050\001\002\000\004\016\051" +
    "\001\002\000\004\013\052\001\002\000\006\030\054\041" +
    "\053\001\002\000\004\013\ufff7\001\002\000\004\013\ufff8" +
    "\001\002\000\004\013\056\001\002\000\004\027\057\001" +
    "\002\000\004\013\060\001\002\000\004\033\061\001\002" +
    "\000\004\013\062\001\002\000\004\016\063\001\002\000" +
    "\004\013\064\001\002\000\006\030\054\041\053\001\002" +
    "\000\004\013\066\001\002\000\004\024\067\001\002\000" +
    "\004\026\070\001\002\000\004\024\071\001\002\000\004" +
    "\004\072\001\002\000\004\031\073\001\002\000\004\014" +
    "\074\001\002\000\004\005\075\001\002\000\004\002\ufffc" +
    "\001\002\000\004\005\077\001\002\000\004\023\100\001" +
    "\002\000\004\013\101\001\002\000\004\036\102\001\002" +
    "\000\004\013\103\001\002\000\004\016\104\001\002\000" +
    "\004\025\105\001\002\000\004\023\106\001\002\000\004" +
    "\013\107\001\002\000\004\032\110\001\002\000\004\013" +
    "\111\001\002\000\004\016\112\001\002\000\004\013\113" +
    "\001\002\000\006\030\054\041\053\001\002\000\004\013" +
    "\115\001\002\000\004\027\116\001\002\000\004\013\117" +
    "\001\002\000\004\033\120\001\002\000\004\013\121\001" +
    "\002\000\004\016\122\001\002\000\004\013\123\001\002" +
    "\000\006\030\054\041\053\001\002\000\004\013\125\001" +
    "\002\000\004\027\126\001\002\000\004\013\127\001\002" +
    "\000\004\034\130\001\002\000\004\013\131\001\002\000" +
    "\004\016\132\001\002\000\004\013\133\001\002\000\004" +
    "\041\134\001\002\000\006\013\ufff4\041\ufff6\001\002\000" +
    "\004\013\136\001\002\000\004\027\137\001\002\000\004" +
    "\013\140\001\002\000\004\035\141\001\002\000\004\013" +
    "\142\001\002\000\004\016\143\001\002\000\004\013\144" +
    "\001\002\000\004\041\134\001\002\000\004\013\146\001" +
    "\002\000\004\024\147\001\002\000\004\026\150\001\002" +
    "\000\004\024\151\001\002\000\004\004\152\001\002\000" +
    "\004\031\153\001\002\000\004\014\154\001\002\000\004" +
    "\005\155\001\002\000\004\002\ufff9\001\002\000\004\041" +
    "\134\001\002\000\004\013\ufff5\001\002\000\004\005\161" +
    "\001\002\000\004\023\162\001\002\000\004\013\163\001" +
    "\002\000\004\036\164\001\002\000\004\013\165\001\002" +
    "\000\004\016\166\001\002\000\004\025\167\001\002\000" +
    "\004\023\170\001\002\000\004\013\171\001\002\000\004" +
    "\032\172\001\002\000\004\013\173\001\002\000\004\016" +
    "\174\001\002\000\004\013\175\001\002\000\006\030\054" +
    "\041\053\001\002\000\004\013\177\001\002\000\004\024" +
    "\200\001\002\000\004\026\201\001\002\000\004\024\202" +
    "\001\002\000\004\004\203\001\002\000\004\031\204\001" +
    "\002\000\004\014\205\001\002\000\004\005\206\001\002" +
    "\000\004\002\ufffa\001\002\000\004\005\210\001\002\000" +
    "\004\023\211\001\002\000\004\013\212\001\002\000\004" +
    "\036\213\001\002\000\004\013\214\001\002\000\004\016" +
    "\215\001\002\000\004\025\216\001\002\000\004\023\217" +
    "\001\002\000\004\013\220\001\002\000\004\037\221\001" +
    "\002\000\004\013\222\001\002\000\004\016\223\001\002" +
    "\000\004\013\224\001\002\000\006\030\054\041\053\001" +
    "\002\000\004\013\226\001\002\000\004\027\227\001\002" +
    "\000\004\013\230\001\002\000\004\017\231\001\002\000" +
    "\004\013\232\001\002\000\004\016\233\001\002\000\004" +
    "\013\234\001\002\000\006\030\054\041\053\001\002\000" +
    "\004\013\236\001\002\000\004\027\237\001\002\000\004" +
    "\013\240\001\002\000\004\040\241\001\002\000\004\013" +
    "\242\001\002\000\004\016\243\001\002\000\004\013\244" +
    "\001\002\000\006\030\054\041\053\001\002\000\004\013" +
    "\246\001\002\000\004\024\247\001\002\000\004\026\250" +
    "\001\002\000\004\024\251\001\002\000\004\004\252\001" +
    "\002\000\004\031\253\001\002\000\004\014\254\001\002" +
    "\000\004\005\255\001\002\000\004\002\ufffb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\253\000\014\002\010\003\005\004\004\005\003\006" +
    "\006\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\054\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\064\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\007\113\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\007\123\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\010\134\001" +
    "\001\000\004\011\155\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\010\144" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\156\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\175" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\224\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\234\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\244\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$S_Analyzer_main$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$S_Analyzer_main$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$S_Analyzer_main$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public String requestName = null;
    public static LinkedList<login> loginList = new LinkedList<login>();

    //Metodo al que se llama automaticamente ante algun error sintactico
    public void syntax_error(Symbol s)
    {
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;

        System.out.println("!!!!!!! Error Sintactico Recuperado !!!!!!!");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);

        login data = new login("error", "errror");
        loginList.add(0, data);
        requestName = "error";
    }

    //Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;

        System.out.println("!!!!!!! Error Sintactico, Panic Mode !!!!!!! ");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);

        login data = new login("error", "errror");
        loginList.add(0, data);
        requestName = "error";
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$S_Analyzer_main$actions {


    void getRequestName(String requestName)
    {
        System.out.println("Nombre de la solicitud: "+requestName);
    }

  private final S_Analyzer_main parser;

  /** Constructor */
  CUP$S_Analyzer_main$actions(S_Analyzer_main parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$S_Analyzer_main$do_action_part00000000(
    int                        CUP$S_Analyzer_main$act_num,
    java_cup.runtime.lr_parser CUP$S_Analyzer_main$parser,
    java.util.Stack            CUP$S_Analyzer_main$stack,
    int                        CUP$S_Analyzer_main$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$S_Analyzer_main$result;

      /* select the action based on the action number */
      switch (CUP$S_Analyzer_main$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-1)).value;
		RESULT = start_val;
              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-1)), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$S_Analyzer_main$parser.done_parsing();
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= USUARIONUEVO 
            {
              String RESULT =null;

              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= MODIFICARUSUARIO 
            {
              String RESULT =null;

              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INICIO ::= ELIMINARUSUARIO 
            {
              String RESULT =null;

              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INICIO ::= LOGINUSUARIO 
            {
              String RESULT =null;

              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // LOGINUSUARIO ::= LessThan QuestionMark XSONsentence Version Equal QuotationMark VersionNumber QuotationMark QuestionMark GreaterThan LessThan ExclamationMark RealizarSolicitud Colon QuotationMark LoginUsuario QuotationMark GreaterThan LeftBrace QuotationMark DatosUsuario QuotationMark Colon LeftBracket LeftBrace QuotationMark Usuario QuotationMark Colon QuotationMark VALUES QuotationMark Comma QuotationMark Password QuotationMark Colon QuotationMark VALUES QuotationMark RightBrace RightBracket RightBrace LessThan FinSolicitud ExclamationMark GreaterThan 
            {
              String RESULT =null;
		int usernameleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-16)).left;
		int usernameright = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-16)).right;
		String username = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-16)).value;
		int passwordleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-8)).left;
		int passwordright = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-8)).right;
		String password = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-8)).value;
		System.out.println("Sentencia de login reconocida y aceptada");
                   requestName = "login";
                   login data = new login(username, password);
                   loginList.add(0, data);
              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("LOGINUSUARIO",4, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-46)), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // MODIFICARUSUARIO ::= LessThan QuestionMark XSONsentence Version Equal QuotationMark VersionNumber QuotationMark QuestionMark GreaterThan LessThan ExclamationMark RealizarSolicitud Colon QuotationMark ModificarUsuario QuotationMark GreaterThan LeftBrace QuotationMark DatosUsuario QuotationMark Colon LeftBracket LeftBrace QuotationMark UsuarioAntiguo QuotationMark Colon QuotationMark VALUES QuotationMark Comma QuotationMark UsuarioNuevo QuotationMark Colon QuotationMark VALUES QuotationMark Comma QuotationMark NuevoPassword QuotationMark Colon QuotationMark VALUES QuotationMark RightBrace RightBracket RightBrace LessThan FinSolicitud ExclamationMark GreaterThan 
            {
              String RESULT =null;
		System.out.println("Sentencia de modificacion de usuario reconocida y aceptada");
                    requestName = "modificar";
              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("MODIFICARUSUARIO",2, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-54)), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ELIMINARUSUARIO ::= LessThan QuestionMark XSONsentence Version Equal QuotationMark VersionNumber QuotationMark QuestionMark GreaterThan LessThan ExclamationMark RealizarSolicitud Colon QuotationMark EliminarUsuario QuotationMark GreaterThan LeftBrace QuotationMark DatosUsuario QuotationMark Colon LeftBracket LeftBrace QuotationMark Usuario QuotationMark Colon QuotationMark VALUES QuotationMark RightBrace RightBracket RightBrace LessThan FinSolicitud ExclamationMark GreaterThan 
            {
              String RESULT =null;
		System.out.println("Sentencia de eliminacion de usuario reconocida y aceptada");
                    requestName = "eliminar";
              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("ELIMINARUSUARIO",3, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-38)), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // USUARIONUEVO ::= LessThan QuestionMark XSONsentence Version Equal QuotationMark VersionNumber QuotationMark QuestionMark GreaterThan LessThan ExclamationMark RealizarSolicitud Colon QuotationMark UsuarioNuevo QuotationMark GreaterThan LeftBrace QuotationMark DatosUsuario QuotationMark Colon LeftBracket LeftBrace QuotationMark Usuario QuotationMark Colon QuotationMark VALUES QuotationMark Comma QuotationMark Password QuotationMark Colon QuotationMark VALUES QuotationMark Comma QuotationMark Nombre QuotationMark Colon QuotationMark NAMES QuotationMark Comma QuotationMark Institucion QuotationMark Colon QuotationMark NAMES QuotationMark RightBrace RightBracket RightBrace LessThan FinSolicitud ExclamationMark GreaterThan 
            {
              String RESULT =null;
		System.out.println("Sentencia de creacion de usuario reconocida y aceptada");
                requestName = "nuevo";
              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("USUARIONUEVO",1, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-62)), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // VALUES ::= Values 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer_main$stack.peek()).value;
		RESULT = String.valueOf(a);
              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("VALUES",5, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // VALUES ::= niValue 
            {
              String RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer_main$stack.peek()).value;
		RESULT = String.valueOf(b);
              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("VALUES",5, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$0 ::= 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer_main$stack.peek()).value;
RESULT = String.valueOf(a);
              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("NT$0",7, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // NAMES ::= niValue NT$0 NAMES 
            {
              String RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (String) ((java_cup.runtime.Symbol) CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-2)).value;

              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("NAMES",6, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.elementAt(CUP$S_Analyzer_main$top-2)), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // NAMES ::= niValue 
            {
              String RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer_main$stack.peek()).value;
		RESULT = String.valueOf(b);
              CUP$S_Analyzer_main$result = parser.getSymbolFactory().newSymbol("NAMES",6, ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer_main$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer_main$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$S_Analyzer_main$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$S_Analyzer_main$do_action(
    int                        CUP$S_Analyzer_main$act_num,
    java_cup.runtime.lr_parser CUP$S_Analyzer_main$parser,
    java.util.Stack            CUP$S_Analyzer_main$stack,
    int                        CUP$S_Analyzer_main$top)
    throws java.lang.Exception
    {
              return CUP$S_Analyzer_main$do_action_part00000000(
                               CUP$S_Analyzer_main$act_num,
                               CUP$S_Analyzer_main$parser,
                               CUP$S_Analyzer_main$stack,
                               CUP$S_Analyzer_main$top);
    }
}

}
