
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

/** CUP generated class containing symbol constants. */
public class Symbols_main {
  /* terminals */
  public static final int Nombre = 26;
  public static final int Institucion = 27;
  public static final int Comma = 21;
  public static final int RealizarSolicitud = 11;
  public static final int RightBrace = 18;
  public static final int DatosUsuario = 28;
  public static final int UsuarioAntiguo = 29;
  public static final int ParametrosTrivia = 37;
  public static final int Password = 25;
  public static final int GreaterThan = 3;
  public static final int Equal = 5;
  public static final int IDTrivia = 43;
  public static final int NuevaTrivia = 36;
  public static final int Tema = 40;
  public static final int ExclamationMark = 10;
  public static final int UsuarioCreacion = 41;
  public static final int LeftBracket = 19;
  public static final int IDTriviaSentence = 38;
  public static final int QuestionMark = 4;
  public static final int FinSolicitud = 23;
  public static final int QuotationMark = 9;
  public static final int TiempoPregunta = 39;
  public static final int RightBracket = 20;
  public static final int Colon = 12;
  public static final int UsuarioNuevo = 13;
  public static final int FinSolicitudes = 34;
  public static final int ListaTrivias = 44;
  public static final int Values = 22;
  public static final int EOF = 0;
  public static final int VersionNumber = 8;
  public static final int error = 1;
  public static final int LeftBrace = 17;
  public static final int Time = 42;
  public static final int Usuario = 24;
  public static final int LessThan = 2;
  public static final int NuevoPassword = 30;
  public static final int ModificarUsuario = 14;
  public static final int Date = 33;
  public static final int Version = 7;
  public static final int FechaCreacion = 32;
  public static final int LoginUsuario = 16;
  public static final int RealizarSolicitudes = 35;
  public static final int XSONsentence = 6;
  public static final int EliminarUsuario = 15;
  public static final int niValue = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LessThan",
  "GreaterThan",
  "QuestionMark",
  "Equal",
  "XSONsentence",
  "Version",
  "VersionNumber",
  "QuotationMark",
  "ExclamationMark",
  "RealizarSolicitud",
  "Colon",
  "UsuarioNuevo",
  "ModificarUsuario",
  "EliminarUsuario",
  "LoginUsuario",
  "LeftBrace",
  "RightBrace",
  "LeftBracket",
  "RightBracket",
  "Comma",
  "Values",
  "FinSolicitud",
  "Usuario",
  "Password",
  "Nombre",
  "Institucion",
  "DatosUsuario",
  "UsuarioAntiguo",
  "NuevoPassword",
  "niValue",
  "FechaCreacion",
  "Date",
  "FinSolicitudes",
  "RealizarSolicitudes",
  "NuevaTrivia",
  "ParametrosTrivia",
  "IDTriviaSentence",
  "TiempoPregunta",
  "Tema",
  "UsuarioCreacion",
  "Time",
  "IDTrivia",
  "ListaTrivias"
  };
}

