
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

/** CUP generated class containing symbol constants. */
public class Symbols_Users {
  /* terminals */
  public static final int QuotationMark = 7;
  public static final int UPValue = 15;
  public static final int Init = 9;
  public static final int Colon = 8;
  public static final int NIValue = 14;
  public static final int LeftBrace = 4;
  public static final int Name = 12;
  public static final int EOF = 0;
  public static final int RightBrace = 5;
  public static final int Password = 11;
  public static final int OpenParenthesis = 2;
  public static final int Institution = 13;
  public static final int error = 1;
  public static final int User = 10;
  public static final int Comma = 6;
  public static final int CloseParenthesis = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OpenParenthesis",
  "CloseParenthesis",
  "LeftBrace",
  "RightBrace",
  "Comma",
  "QuotationMark",
  "Colon",
  "Init",
  "User",
  "Password",
  "Name",
  "Institution",
  "NIValue",
  "UPValue"
  };
}

